"""Export renderers: working palette -> theme files for other terminals.

Every renderer is a pure ``Palette -> str`` function (trailing newline,
deterministic, no I/O, importable without ``gi``).  The UI owns file
writing so an export only ever lands where the user chose; nothing here
touches another tool's config or Omarchy-managed state.

Hex conventions differ per target: foot wants bare hex, every other
format takes ``#rrggbb``.  Role mapping matches the Omarchy pipeline
(cursor block = ``cursor``, cursor text = ``background``) throughout.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass

from .palette import Palette

__all__ = ["FormatSpec", "FORMATS", "suggested_basename", "render"]


@dataclass(frozen=True)
class FormatSpec:
    """One export target: registry id, human label, suggested filename."""

    id: str
    label: str
    filename: str


FORMATS: list[FormatSpec] = [
    FormatSpec("foot", "Foot (foot.ini)", "foot.ini"),
    FormatSpec("alacritty", "Alacritty (alacritty.toml)", "alacritty.toml"),
    FormatSpec("ghostty", "Ghostty (ghostty.conf)", "ghostty.conf"),
    FormatSpec("kitty", "Kitty (kitty.conf)", "kitty.conf"),
    FormatSpec("wezterm", "WezTerm (colorscheme .lua)", "wezterm.lua"),
    FormatSpec("json", "Raw palette (.json, any terminal)", "palette.json"),
]


def suggested_basename(fmt_id: str, title: str) -> str:
    """'<title>.ini' style basename for the save dialog.

    Falls back to the format's default filename when the title slugifies
    to nothing.
    """
    spec = next((f for f in FORMATS if f.id == fmt_id), FORMATS[0])
    stem = _slug(title)
    return f"{stem}.{spec.filename.split('.', 1)[1]}" if stem else spec.filename


# --------------------------------------------------------------------------
# renderers
# --------------------------------------------------------------------------

def _bare(hexcolor: str) -> str:
    return hexcolor.lstrip("#")


_ANSI_NAMES = ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")


def _slug(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.strip().lower()).strip("-")
    return slug[:64]


def _footer(title: str) -> str:
    t = title.strip() or "Untitled"
    return f"Generated by Terminal Theme Studio from “{t}”."


def _foot(p: Palette, title: str) -> str:
    lines = [
        f"# {_footer(title)}",
        "# Point foot.ini at this file:  [main]\\ninclude=<path to this file>",
        "[colors-dark]",
        f"foreground={_bare(p.foreground)}",
        f"background={_bare(p.background)}",
        f"selection-foreground={_bare(p.selection_fg)}",
        f"selection-background={_bare(p.selection_bg)}",
        "",
        f"cursor={_bare(p.background)} {_bare(p.cursor)}",
        "",
    ]
    lines += [f"regular{i}={_bare(getattr(p, f'regular{i}'))}" for i in range(8)]
    lines += [f"bright{i}={_bare(getattr(p, f'bright{i}'))}" for i in range(8)]
    return "\n".join(lines) + "\n"


def _alacritty(p: Palette, title: str) -> str:
    def s(h: str) -> str:
        return f'"{h}"'

    lines = [
        f"# {_footer(title)}",
        "# Merge into alacritty.toml, or import: [general] import = [\"<path>\"]",
        "[colors.primary]",
        f"background = {s(p.background)}",
        f"foreground = {s(p.foreground)}",
        "",
        "[colors.cursor]",
        f"text = {s(p.background)}",
        f"cursor = {s(p.cursor)}",
        "",
        "[colors.vi_mode_cursor]",
        f"text = {s(p.background)}",
        f"cursor = {s(p.cursor)}",
        "",
        "[colors.selection]",
        f"text = {s(p.selection_fg)}",
        f"background = {s(p.selection_bg)}",
        "",
        "[colors.normal]",
    ]
    for i, name in enumerate(_ANSI_NAMES):
        lines.append(f"{name} = {s(getattr(p, f'regular{i}'))}")
    lines += ["", "[colors.bright]"]
    for i, name in enumerate(_ANSI_NAMES):
        lines.append(f"{name} = {s(getattr(p, f'bright{i}'))}")
    return "\n".join(lines) + "\n"


def _ghostty(p: Palette, title: str) -> str:
    lines = [
        f"# {_footer(title)}",
        "# Include from the ghostty config:  config-file = <path to this file>",
        f"background = {p.background}",
        f"foreground = {p.foreground}",
        f"cursor-color = {p.cursor}",
        f"selection-background = {p.selection_bg}",
        f"selection-foreground = {p.selection_fg}",
    ]
    for i in range(16):
        role = f"regular{i}" if i < 8 else f"bright{i - 8}"
        lines.append(f"palette = {i}={getattr(p, role)}")
    return "\n".join(lines) + "\n"


def _kitty(p: Palette, title: str) -> str:
    lines = [
        f"# {_footer(title)}",
        "# Include from kitty.conf:  include <path to this file>",
        f"foreground = {p.foreground}",
        f"background = {p.background}",
        f"cursor = {p.cursor}",
        f"cursor_text_color = {p.background}",
        f"selection_foreground = {p.selection_fg}",
        f"selection_background = {p.selection_bg}",
    ]
    for i in range(16):
        role = f"regular{i}" if i < 8 else f"bright{i - 8}"
        lines.append(f"color{i} = {getattr(p, role)}")
    return "\n".join(lines) + "\n"


def _wezterm(p: Palette, title: str) -> str:
    def a(hexes: list[str]) -> str:
        return ",\n".join(f"    '{h}'" for h in hexes)

    t = title.strip() or "Untitled"
    slug = _slug(t) or "custom"
    return (
        f"-- {_footer(title)}\n"
        "-- Either save as its own module and `local colors = require('<this file>')`,\n"
        "-- or paste the table into ~/.wezterm.lua and add:\n"
        f"--   config.color_schemes['{slug}'] = colors\n"
        f"--   config.color_scheme = '{slug}'\n"
        "local colors = {\n"
        f"  foreground = '{p.foreground}',\n"
        f"  background = '{p.background}',\n"
        f"  cursor_bg = '{p.cursor}',\n"
        f"  cursor_fg = '{p.background}',\n"
        f"  cursor_border = '{p.cursor}',\n"
        f"  selection_fg = '{p.selection_fg}',\n"
        f"  selection_bg = '{p.selection_bg}',\n"
        "  ansi = {\n"
        f"{a([getattr(p, f'regular{i}') for i in range(8)])},\n"
        "  },\n"
        "  brights = {\n"
        f"{a([getattr(p, f'bright{i}') for i in range(8)])},\n"
        "  },\n"
        "}\n"
        "return colors\n"
    )


def _json(p: Palette, title: str) -> str:
    data = {"name": title.strip() or "Untitled"}
    data.update(p.to_dict())
    return json.dumps(data, indent=2) + "\n"


_RENDER = {
    "foot": _foot,
    "alacritty": _alacritty,
    "ghostty": _ghostty,
    "kitty": _kitty,
    "wezterm": _wezterm,
    "json": _json,
}


def render(fmt_id: str, palette: Palette, title: str = "") -> str:
    """Render ``palette`` in the format registered under ``fmt_id``."""
    try:
        fn = _RENDER[fmt_id]
    except KeyError:
        raise ValueError(f"unknown export format: {fmt_id!r}") from None
    return fn(palette, title or "")
